# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170522_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Всі товари'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категорія товару', 'verbose_name_plural': 'Категорія товарів'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотографія', 'verbose_name_plural': 'Фотографії'},
        ),
    ]
